// Golden replays: definitions and the engine-independent checker (GAME_DESIGN.md §10.7). Owner: O1.
// Shared by tests/sim/golden.test.ts (Node), tests/browser/golden.browser.test.ts (chromium / firefox /
// webkit) and tests/worker/golden.worker.test.ts (workerd). Uses only src/sim and the bots, no DOM / Node APIs.
import { b64urlDecode, b64urlEncode } from '../../src/sim/b64';
import { SIM_VERSION } from '../../src/sim/constants';
import { levelHash, type LevelPhysics } from '../../src/sim/level';
import { decodeReplay, DeviceTag, encodeReplay, simulateReplay, type ReplayResult } from '../../src/sim/replay';
import {
  bangBang, carry, dashBrake, pump, randomSeeded, randomWalk, runBot, slackSnap, slamStop, type Policy,
} from './bots';
import { f64hex } from './detmath_vectors';

export interface GoldenExpect {
  status: number; ticks: number; score: number | null;
  minD2: string; peakF: string; // float64 bit patterns (minD2 may be +Infinity)
  crash: { kind: number; wall: number; px: string; py: string; d2: string } | null;
  stateHash: number;
  events: Record<string, number>; // event kind -> count (documentation / coverage)
}
export interface GoldenEntry { id: string; level: string; bot: string; maxTicks: number; replay: string; expect: GoldenExpect }
export interface GoldenFile { format: 1; sim: number; about: string; levels: Record<string, LevelPhysics>; replays: GoldenEntry[] }

type BotDef = { id: string; level: string; bot: string; maxTicks: number; make: ((p: LevelPhysics) => Policy) | null };

/**
 * The 20 golden replays on 6 levels. `make: null` = recorded input (built once from the research plans
 * in plans_py.json by golden.test.ts and then kept verbatim), everything else is regenerated by its bot.
 */
export const GOLDEN_BOTS: BotDef[] = [
  { id: '1-1/bang-bang', level: '1-1', bot: 'bangBang(17, 11)', maxTicks: 900, make: bangBang(17, 11) },
  { id: '1-1/carry', level: '1-1', bot: 'carry(1.5)', maxTicks: 1200, make: carry(1.5) },
  { id: '1-1/slack-snap', level: '1-1', bot: 'slackSnap(40, 25)', maxTicks: 900, make: slackSnap(40, 25) },
  { id: '1-1/random', level: '1-1', bot: 'randomSeeded(11)', maxTicks: 600, make: randomSeeded(11) },
  { id: '1-1/random-walk', level: '1-1', bot: 'randomWalk(1001)', maxTicks: 600, make: randomWalk(1001) },
  { id: '2-2/ai-open-loop', level: '2-2', bot: 'recorded: plans_py 2-2/ai force at 60 Hz + fine servo with assist', maxTicks: 1800, make: null },
  { id: '2-2/dash-brake', level: '2-2', bot: 'dashBrake(1.63)', maxTicks: 600, make: dashBrake(1.63) },
  { id: '2-2/pump', level: '2-2', bot: 'pump(240, 1.63)', maxTicks: 900, make: pump(240, 1.63) },
  { id: '3-3/pump', level: '3-3', bot: 'pump(300, 1.28)', maxTicks: 900, make: pump(300, 1.28) },
  { id: '3-3/carry-away', level: '3-3', bot: 'carry(-0.5)', maxTicks: 3600, make: carry(-0.5) },
  { id: '3-3/random', level: '3-3', bot: 'randomSeeded(33)', maxTicks: 600, make: randomSeeded(33) },
  { id: '4-2/slam-stop', level: '4-2', bot: 'slamStop()', maxTicks: 600, make: slamStop() },
  { id: '4-2/dash-brake', level: '4-2', bot: 'dashBrake(2.34)', maxTicks: 600, make: dashBrake(2.34) },
  { id: '4-2/random', level: '4-2', bot: 'randomSeeded(42)', maxTicks: 600, make: randomSeeded(42) },
  { id: '4-3/carry', level: '4-3', bot: 'carry(1.8)', maxTicks: 900, make: carry(1.8) },
  { id: '4-3/random', level: '4-3', bot: 'randomSeeded(43)', maxTicks: 600, make: randomSeeded(43) },
  { id: '5-4/full-course', level: '5-4', bot: 'recorded: plans_py 2-2/ai + hold, then escape_fast + hold', maxTicks: 3600, make: null },
  { id: '5-4/slack-snap', level: '5-4', bot: 'slackSnap(30, 20)', maxTicks: 900, make: slackSnap(30, 20) },
  { id: '5-4/pump', level: '5-4', bot: 'pump(300, 1.63)', maxTicks: 900, make: pump(300, 1.63) },
  { id: '5-4/random', level: '5-4', bot: 'randomSeeded(54)', maxTicks: 600, make: randomSeeded(54) },
];

/** Replay text of a q sequence: b64url(encodeReplay) with device Unknown, no flags, the current SIM_VERSION. */
export function replayText(phys: LevelPhysics, qs: Int8Array): string {
  return b64urlEncode(encodeReplay({ fmt: 1, sim: SIM_VERSION, levelHash: levelHash(phys), device: DeviceTag.Unknown, flags: 0, nTicks: qs.length }, qs));
}

/** Simulates and summarises a q sequence the way golden_replays.json stores it. */
export function expectOf(phys: LevelPhysics, qs: Int8Array): GoldenExpect {
  const events: Record<string, number> = {};
  const r: ReplayResult = simulateReplay(phys, qs, {
    onTick(_t, _s, ev) {
      for (let i = 0; i < ev.n; i++) {
        const k = String(ev.kind[i]);
        events[k] = (events[k] ?? 0) + 1;
      }
    },
  });
  return {
    status: r.status,
    ticks: r.ticks,
    score: r.score,
    minD2: f64hex(r.minD2),
    peakF: f64hex(r.peakF),
    crash: r.crash
      ? { kind: r.crash.kind, wall: r.crash.wall, px: f64hex(r.crash.px), py: f64hex(r.crash.py), d2: f64hex(r.crash.d2) }
      : null,
    stateHash: r.stateHash,
    events,
  };
}

/** Regenerates a bot's q sequence (null for recorded entries). */
export function botReplay(def: BotDef, phys: LevelPhysics): Int8Array | null {
  return def.make ? runBot(phys, def.make(phys), def.maxTicks) : null;
}

/**
 * Checks every stored replay against this engine: the re-simulation summary (incl. stateHash) must equal the
 * stored one, the replay header must carry the level's hash, and each bot must regenerate exactly the stored
 * q sequence. Returns human-readable mismatches (empty = pass).
 */
export function checkGolden(g: GoldenFile, opts: { regenerateBots: boolean } = { regenerateBots: true }): string[] {
  const bad: string[] = [];
  if (g.sim !== SIM_VERSION) bad.push(`golden made with sim ${g.sim}, running sim ${SIM_VERSION}`);
  if (g.replays.length !== GOLDEN_BOTS.length) bad.push(`expected ${GOLDEN_BOTS.length} replays, file has ${g.replays.length}`);
  for (const e of g.replays) {
    const phys = g.levels[e.level];
    if (!phys) {
      bad.push(`${e.id}: no physics for level ${e.level}`);
      continue;
    }
    let qs: Int8Array;
    try {
      const d = decodeReplay(b64urlDecode(e.replay));
      if (d.h.levelHash !== levelHash(phys)) bad.push(`${e.id}: header hash ${d.h.levelHash} != ${levelHash(phys)}`);
      qs = d.qs;
    } catch (err) {
      bad.push(`${e.id}: undecodable replay (${String(err)})`);
      continue;
    }
    const got = expectOf(phys, qs);
    if (JSON.stringify(got) !== JSON.stringify(e.expect)) {
      bad.push(`${e.id}: got ${JSON.stringify(got)} want ${JSON.stringify(e.expect)}`);
    }
    if (opts.regenerateBots) {
      const def = GOLDEN_BOTS.find((b) => b.id === e.id);
      if (!def) {
        bad.push(`${e.id}: unknown bot`);
        continue;
      }
      const again = botReplay(def, phys);
      if (again && replayText(phys, again) !== e.replay) bad.push(`${e.id}: bot ${def.bot} produced a different q sequence`);
    }
  }
  return bad;
}
